{
  "backend": {
    "name": "git-gateway",
    "accept_roles": [
      "admin",
      "editor"
    ]
  },
  "media_folder": "static/images/uploads",
  "collections": [
    {
      "name": "pages",
      "label": "Pages",
      "folder": "site/pages",
      "create": false,
      "delete": false,
      "slug": "{{slug}}",
      "editor": {
        "preview": false
      },
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Layout",
          "widget": "hidden",
          "name": "layout",
          "default": "{{slug}}.html"
        },
        {
          "label": "Seo",
          "name": "seo",
          "widget": "object",
          "fields": [
            {
              "label": "Title",
              "name": "title",
              "widget": "string",
              "required": false
            },
            {
              "label": "Description",
              "name": "description",
              "widget": "string",
              "required": false
            },
            {
              "label": "Open Graph Image",
              "name": "og:image",
              "widget": "image",
              "required": false,
              "media_library": {
                "config": {
                  "multiple": false
                }
              }
            },
            {
              "label": "Twitter Card",
              "name": "twitter:card",
              "widget": "string",
              "default": "summary",
              "required": false
            },
            {
              "label": "Twitter Site",
              "name": "twitter:site",
              "widget": "string",
              "required": false
            },
            {
              "label": "Twitter Creator",
              "name": "twitter:creator",
              "widget": "string",
              "required": false
            },
            {
              "label": "Additional HTML tags",
              "name": "additional_tags",
              "widget": "text",
              "required": false
            }
          ]
        }
      ]
    },
    {
      "name": "client-projects",
      "label": "Client projects",
      "folder": "site/client-projects",
      "create": true,
      "slug": "{{slug}}",
      "editor": {
        "preview": false
      },
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Tags",
          "widget": "hidden",
          "name": "tags",
          "default": "client-projects"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Layout",
          "widget": "hidden",
          "name": "layout",
          "default": "single-client-projects.html"
        },
        {
          "label": "Seo",
          "name": "seo",
          "widget": "object",
          "fields": [
            {
              "label": "Title",
              "name": "title",
              "widget": "string",
              "required": false
            },
            {
              "label": "Description",
              "name": "description",
              "widget": "string",
              "required": false
            },
            {
              "label": "Open Graph Image",
              "name": "og:image",
              "widget": "image",
              "required": false,
              "media_library": {
                "config": {
                  "multiple": false
                }
              }
            },
            {
              "label": "Twitter Card",
              "name": "twitter:card",
              "widget": "string",
              "default": "summary",
              "required": false
            },
            {
              "label": "Twitter Site",
              "name": "twitter:site",
              "widget": "string",
              "required": false
            },
            {
              "label": "Twitter Creator",
              "name": "twitter:creator",
              "widget": "string",
              "required": false
            },
            {
              "label": "Additional HTML tags",
              "name": "additional_tags",
              "widget": "text",
              "required": false
            }
          ]
        },
        {
          "name": "client-testimonial",
          "label": "Client testimonial",
          "widget": "text",
          "required": false
        },
        {
          "name": "featured-image",
          "label": "Featured image",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "project-summary",
          "label": "Project summary",
          "widget": "text",
          "required": false
        },
        {
          "name": "project-details",
          "label": "Project details",
          "widget": "text",
          "required": false
        },
        {
          "name": "location",
          "label": "Location",
          "widget": "text",
          "required": false
        },
        {
          "name": "type-of-project",
          "label": "Type of project",
          "widget": "text",
          "required": false
        },
        {
          "name": "date-completed",
          "label": "Date completed",
          "widget": "text",
          "required": false
        },
        {
          "name": "additional-project-images",
          "label": "Additional project images",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": true
            }
          }
        },
        {
          "label": "Body",
          "name": "body",
          "widget": "markdown",
          "required": false
        }
      ]
    },
    {
      "name": "team-members",
      "label": "Team members",
      "folder": "site/team-members",
      "create": true,
      "slug": "{{slug}}",
      "editor": {
        "preview": false
      },
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Tags",
          "widget": "hidden",
          "name": "tags",
          "default": "team-members"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Layout",
          "widget": "hidden",
          "name": "layout",
          "default": "single-team-members.html"
        },
        {
          "label": "Seo",
          "name": "seo",
          "widget": "object",
          "fields": [
            {
              "label": "Title",
              "name": "title",
              "widget": "string",
              "required": false
            },
            {
              "label": "Description",
              "name": "description",
              "widget": "string",
              "required": false
            },
            {
              "label": "Open Graph Image",
              "name": "og:image",
              "widget": "image",
              "required": false,
              "media_library": {
                "config": {
                  "multiple": false
                }
              }
            },
            {
              "label": "Twitter Card",
              "name": "twitter:card",
              "widget": "string",
              "default": "summary",
              "required": false
            },
            {
              "label": "Twitter Site",
              "name": "twitter:site",
              "widget": "string",
              "required": false
            },
            {
              "label": "Twitter Creator",
              "name": "twitter:creator",
              "widget": "string",
              "required": false
            },
            {
              "label": "Additional HTML tags",
              "name": "additional_tags",
              "widget": "text",
              "required": false
            }
          ]
        },
        {
          "name": "image",
          "label": "Image",
          "widget": "image",
          "required": false,
          "media_library": {
            "config": {
              "multiple": false
            }
          }
        },
        {
          "name": "client-projects",
          "label": "Client projects",
          "widget": "relation",
          "collection": "client-projects",
          "searchFields": [
            "title"
          ],
          "valueField": "slug",
          "displayFields": [
            "title"
          ],
          "required": false
        },
        {
          "name": "bio",
          "label": "Bio",
          "widget": "text",
          "required": false
        },
        {
          "label": "Body",
          "name": "body",
          "widget": "markdown",
          "required": false
        }
      ]
    }
  ]
}